name: 'Zeta Pass Build Pipeline'

on:
  workflow_dispatch: # GitHub üzerinden butona basarak manuel çalıştırmayı sağlar
  push:
    tags:
      - 'v*' # v1.0.0 gibi bir etiket (tag) gönderdiğinde otomatik çalışır

jobs:
  publish-tauri:
    permissions:
      contents: write # GitHub Releases kısmına dosya yüklemek için gerekli izin
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Cache Rust Dependencies
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Install Frontend Dependencies
        run: npm install

      - name: Build and Publish Tauri App
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v__VERSION__
          releaseName: 'Zeta Password Generator v__VERSION__'
          releaseBody: 'ZetaLabs: Windows Hello entegrasyonlu, tamamen lokal ve güvenli şifre üretici.'
          releaseDraft: false
          prerelease: false
